### ISSUE TITLE
ombi-4.35.18.pkg is running in jail but web interface does not load. 

### ISSUE THREAD

**Issue by Hagya15** [Thefrank/freebsd-port-sooners#20]
i configured the jail and installed the ombi-4.35.18.pkg and even tho the shell in truenas tells me the service is running, the web interface never loads. i uninstalled it and installed the ombi-4.25.0.pkg. the webpage loads perfectly fine. 
I need the newer version because the older versions are not compatible with sonarr v4.

i run the latest stable release of Truenas core, TrueNAS-13.0-U6.1 and the jail is release 13.2-RELEASE-p11

is there something i'm missing?

**Comment by Thefrank** [comment]
The service uses a different UID/GID than the older one but the service should automatically fix some of that.

Does `/usr/local/ombi/Ombi --storage /var/db/ombi` give any any errors?

If it complains about access to the database file than you might need to `chown` the path to the new UID/GID

**Comment by Hagya15** [comment]
it gave an sqlite3 error:




Unhandled exception. System.DllNotFoundException: Unable to load shared library'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Shared object "libe_sqlite3" not found, required by "Ombi"
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at SQLitePCL.Batteries.Init()
   at Ombi.Extensions.DatabaseExtensions.ConfigureSqlite(DbContextOptionsBuilder options, PerDatabaseConfiguration config) in /usr/home/azureagent/vsts/_work/9/s/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 116
   at Ombi.Extensions.DatabaseExtensions.<>c__DisplayClass2_0.<ConfigureDatabases>b__4(DbContextOptionsBuilder x) in /usr/home/azureagent/vsts/_work/9/s/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 53
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)

>

**Comment by Hagya15** [comment]
solved! 
UI loads and i am able to link sonarr v4. 

follow-up question, i want to move the configurations from my old ombi install to the new one. I found the following in the wiki
```
There are 3 important db files (see what they do [here](https://docs.ombi.app/info/faq/#database-uses)).
Ombi.db
OmbiExternal.db
OmbiSettings.db
```
i assume if i copy these database files to the new ombi it should work, but i cant find these files in the ombi directory. 
do you know where these files are stored?

**Comment by Thefrank** [comment]
`/var/db/ombi` (unless changed by editing the variable via sysrc or the rc.d file) should contain your data

**Comment by Hagya15** [comment]
that is the correct location. i copied the files over to the jail with new version of ombi, but i couldnt get it to work so i just manually configured ombi. 

thank you for the help and creating/maintaining this package!
