### ISSUE TITLE
localhost does not resolves into download clients for radarrv3-3.2.2.5080 

### ISSUE THREAD

**Issue by fmunteanu** [Thefrank/freebsd-port-sooners#6]
For simplicity, I have Sonarr, Radarr (your .txz file), Sanbzbd and Transmission installed into same jail, all running under same `user:group`. The service starts and everything is okay, except the download clients are broken if hostname is used instead of IP. Yet they work without issues in Sonarr, which uses Mono 6.8.

The temporary fix is to use the `127.0.0.1` IP address, instead of `localhost`. I'm not happy using an IP, default `localhost` hostname should be working, as it does inside the jail. Like Sonarr, Lidarr, etc.

![image](https://user-images.githubusercontent.com/19806136/136485659-b98e71d0-9af5-45a8-8954-753296ad0efc.png)

```
iocage create -n media -r 12.2-RELEASE allow_mlock=on boot=on dhcp=on vnet=on bpf=yes
```

Inside jail, SABnzbd is functional, otherwise it would not work on Sonarr:

```
root@media:~ # curl -I http://localhost:8080/
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Server: CherryPy/17.4.2
Date: Thu, 07 Oct 2021 20:48:57 GMT
X-Frame-Options: SameOrigin
Vary: Accept-Encoding
Content-Length: 564426
```

Error log when using `localhost` inside web UI:

```
2021-10-07 16:30:06.6|Info|Bootstrap|Starting Radarr - /usr/local/share/radarrv3/Radarr - Version 3.2.2.5080
2021-10-07 16:30:07.4|Info|AppFolderInfo|Data directory is being overridden to [/usr/local/radarr]
2021-10-07 16:30:07.6|Info|Router|Application mode: Interactive
2021-10-07 16:30:07.7|Info|MigrationController|*** Migrating data source=/usr/local/radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-10-07 16:30:08.3|Info|MigrationController|*** Migrating data source=/usr/local/radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-10-07 16:30:08.7|Info|WebHostController|Listening on the following URLs:
2021-10-07 16:30:08.7|Info|WebHostController|  http://*:7878
2021-10-07 16:30:09.2|Info|RadarrBootstrapper|Starting Web Server
2021-10-07 16:30:10.8|Info|CommandExecutor|Starting 2 threads for tasks.
2021-10-07 16:34:41.0|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from SABnzbd

[v3.2.2.5080] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to SABnzbd, Connection reset by peer (localhost:8080): 'http://localhost:8080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json'
---> System.Net.WebException: Connection reset by peer (localhost:8080): 'http://localhost:8080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json'
---> System.Net.WebException: Connection reset by peer (localhost:8080)
---> System.Net.Http.HttpRequestException: Connection reset by peer (localhost:8080)
---> System.Net.Sockets.SocketException (54): Connection reset by peer
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.GetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName)
   at System.Net.Sockets.Socket.get_NoDelay()
   at System.Net.Sockets.Socket.ReplaceHandle()
   at System.Net.Sockets.Socket.ReplaceHandleIfNecessaryAfterFailedConnect()
   at System.Net.Sockets.Socket.ValidateForMultiConnect(Boolean isMultiEndpoint)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<>n__1(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 81
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 107
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 185
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 198
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetQueue(Int32 start, Int32 limit, SabnzbdSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 113
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetQueue() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 57
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetItems()+MoveNext() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 188
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in D:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 89
```

**Comment by Thefrank** [comment]
I can confirm that `localhost` does not resolve inside Radarr regardless of having a service that it can connect to.

**Comment by Thefrank** [comment]
I guess as a final thing check what `host -rsv localhost` returns. does it return the same info? does it try upstream?
